name: Build

on:
  # push:
  #   branches: [ master, dev ]
  # pull_request:
  #   branches: [ master, dev ]
  # schedule:
  #   - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'dev'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        submodules: recursive

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: master
        
    - name: Build
      run: zig build test --summary all

    - name: Benchmark
      run: zig build benchmark -Doptimize=ReleaseFast
