name: Create Release, update README, send announcement


on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set tag name
      id: tag
      run: |
        echo "::set-output name=version::${GITHUB_REF#refs/tags/}"    

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.tag.outputs.version }} # Remove 'refs/tags/' from the tag name
        prerelease: true
